export const CarrelloActionTypes = {
    TOGGLE_ANTEPRIMA: 'TOGGLE_ANTEPRIMA',
    ADD_PRODOTTO: 'ADD_PRODOTTO',
    REMOVE_PRODOTTO: 'REMOVE_PRODOTTO',
    CANCELLA_ELEMENTO: 'CANCELLA_ELEMENTO',
    SVUOTA_CARRELLO: 'SVUOTA_CARRELLO',
    SVUOTA_CARRELLO_FE: 'SVUOTA_CARRELLO_FE',
    RETRIEVE_CARRELLO: 'RETRIEVE_CARRELLO',
};